language: php

php:
  - 5.5
  - 5.4
  - 5.6

matrix:
  fast_finish: true

before_script:
  - git clone -b 1.3.4 git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon/build/safe && phpize && ./configure --enable-phalcon && sudo make install
  - cd ../../../ && phpenv config-add ./spec/phalcon.ini
  - composer self-update
  - composer install --dev --prefer-source
  - phpenv rehash

script: vendor/bin/kahlan
